### ISSUE TITLE
NullPointerException when keyboard closes

### ISSUE THREAD

**Issue by FootballFan141** [windyzboy/CustomEditor#8]
When I click the back button on my phone it crashes the app, any help?
Here's the error
`java.lang.NullPointerException: Attempt to invoke interface method 'void windyzboy.github.io.customeeditor.CustomEditText$EventBack.close()' on a null object reference
                                                                               at windyzboy.github.io.customeeditor.CustomEditText.onKeyPreIme(CustomEditText.java:67)
                                                                               at android.view.View.dispatchKeyEventPreIme(View.java:8405)
                                                                               at android.view.ViewGroup.dispatchKeyEventPreIme(ViewGroup.java:1489)
                                                                               at android.view.ViewGroup.dispatchKeyEventPreIme(ViewGroup.java:1489)
                                                                               at android.view.ViewGroup.dispatchKeyEventPreIme(ViewGroup.java:1489)
                                                                               at android.view.ViewGroup.dispatchKeyEventPreIme(ViewGroup.java:1489)
                                                                               at android.view.ViewGroup.dispatchKeyEventPreIme(ViewGroup.java:1489)
                                                                               at android.view.ViewGroup.dispatchKeyEventPreIme(ViewGroup.java:1489)
                                                                               at android.view.ViewGroup.dispatchKeyEventPreIme(ViewGroup.java:1489)
                                                                               at android.view.ViewRootImpl$ViewPreImeInputStage.processKeyEvent(ViewRootImpl.java:3952)
                                                                               at android.view.ViewRootImpl$ViewPreImeInputStage.onProcess(ViewRootImpl.java:3945)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3652)
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3705)
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3671)
                                                                               at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3803)
                                                                               at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3679)
                                                                               at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3860)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3652)
                                                                               at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6003)
                                                                               at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5977)
                                                                               at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5948)
                                                                               at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6155)
                                                                               at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                               at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                               at android.os.MessageQueue.next(MessageQueue.java:143)
                                                                               at android.os.Looper.loop(Looper.java:122)
                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)`

Here's how I use it:
`final CustomEditText postEditor = (CustomEditText) v.findViewById(R.id.addpost);`
`Dialog d = (Dialog) dialog;`
`Html.fromHtml(postEditor.getTextHTML())`

Thanks for your time :smile:

**Comment by FootballFan141** [comment]
Ooops it was a mistake on my end.

I should of looked at the demo first :grin: 

Thanks for this Editor! :grinning:
